name: Update Publications from Google Scholar

on:
  schedule:
    # Runs every Monday at 6:00 AM UTC
    - cron: '0 6 * * 1'
  workflow_dispatch: # Allow manual trigger from GitHub UI

permissions:
  contents: write

jobs:
  update-publications:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install scholarly

      - name: Fetch publications from Google Scholar
        run: python scripts/fetch_publications.py

      - name: Check for changes
        id: check_changes
        run: |
          git diff --quiet publications.json && echo "changed=false" >> $GITHUB_OUTPUT || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and push if changed
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add publications.json
          git commit -m "Update publications from Google Scholar [automated]"
          git push
